language: android

android:
  components:
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'

script:
    - ./gradlew --full-stacktrace -q clean assemble cobertura uploadArchives

after_success:
    - ls -al build/cobertura/
    - ls -al build/reports/cobertura/coverage.xml
    - cat build/reports/cobertura/coverage.xml
    - ./gradlew coveralls --info
